spring: 
   profiles: 
      active: 
      - dev
      
---
spring: 
   profile: dev
   application: 
      name: microservicecloud-config-dev
      
---
spring: 
   profile: test
   application: 
      name: microservicecloud-config-test
      