spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: mickey
    dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: cn21-microservicecloud
  company.name: cn21.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: mickey
    dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: cn21-microservicecloud
  company.name: cn21.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}